// swift-tools-version:5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "ZenUniffi",
    platforms: [
        .iOS(.v16)
    ],
    products: [
        // Products define the executables and libraries a package produces, making them visible to other packages.
        .library(
            name: "ZenUniffi",
            targets: ["ZenUniffi"]
        )
    ],
    targets: [
        // Swift wrapper target
        // Contains the Swift code generated by UniFFI that wraps the Rust FFI calls
        .target(
            name: "ZenUniffi",
            dependencies: ["ZenUniffiBinary"],
            path: "Sources/ZenUniffi"
        ),

        // Binary target containing the compiled Rust library
        // The XCFramework includes:
        // - libzen_uniffi.a (compiled Rust code)
        // - Headers/zen_uniffiFFI.h (C type definitions)
        // - Headers/zen_uniffiFFI.modulemap (C module map)
        .binaryTarget(
            name: "ZenUniffiBinary",
            path: "ZenUniffi.xcframework"
        )
    ]
)