// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_ZEN_CUSTOM_NODE_CALLBACK_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_ZEN_CUSTOM_NODE_CALLBACK_METHOD0
typedef void (*UniffiCallbackInterfaceZenCustomNodeCallbackMethod0)(uint64_t, RustBuffer, UniffiForeignFutureCompleteRustBuffer _Nonnull, uint64_t, UniffiForeignFuture* _Nonnull
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_ZEN_DECISION_LOADER_CALLBACK_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_ZEN_DECISION_LOADER_CALLBACK_METHOD0
typedef void (*UniffiCallbackInterfaceZenDecisionLoaderCallbackMethod0)(uint64_t, RustBuffer, UniffiForeignFutureCompleteRustBuffer _Nonnull, uint64_t, UniffiForeignFuture* _Nonnull
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_ZEN_CUSTOM_NODE_CALLBACK
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_ZEN_CUSTOM_NODE_CALLBACK
typedef struct UniffiVTableCallbackInterfaceZenCustomNodeCallback {
    UniffiCallbackInterfaceZenCustomNodeCallbackMethod0 _Nonnull handle;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceZenCustomNodeCallback;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_ZEN_DECISION_LOADER_CALLBACK
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_ZEN_DECISION_LOADER_CALLBACK
typedef struct UniffiVTableCallbackInterfaceZenDecisionLoaderCallback {
    UniffiCallbackInterfaceZenDecisionLoaderCallbackMethod0 _Nonnull load;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceZenDecisionLoaderCallback;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_CLONE_ZENDECISION
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_CLONE_ZENDECISION
void*_Nonnull uniffi_zen_uniffi_fn_clone_zendecision(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_FREE_ZENDECISION
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_FREE_ZENDECISION
void uniffi_zen_uniffi_fn_free_zendecision(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_METHOD_ZENDECISION_EVALUATE
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_METHOD_ZENDECISION_EVALUATE
uint64_t uniffi_zen_uniffi_fn_method_zendecision_evaluate(void*_Nonnull ptr, RustBuffer context, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_METHOD_ZENDECISION_VALIDATE
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_METHOD_ZENDECISION_VALIDATE
void uniffi_zen_uniffi_fn_method_zendecision_validate(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_CLONE_ZENENGINE
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_CLONE_ZENENGINE
void*_Nonnull uniffi_zen_uniffi_fn_clone_zenengine(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_FREE_ZENENGINE
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_FREE_ZENENGINE
void uniffi_zen_uniffi_fn_free_zenengine(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_CONSTRUCTOR_ZENENGINE_NEW
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_CONSTRUCTOR_ZENENGINE_NEW
void*_Nonnull uniffi_zen_uniffi_fn_constructor_zenengine_new(RustBuffer loader, RustBuffer custom_node, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_METHOD_ZENENGINE_CREATE_DECISION
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_METHOD_ZENENGINE_CREATE_DECISION
void*_Nonnull uniffi_zen_uniffi_fn_method_zenengine_create_decision(void*_Nonnull ptr, RustBuffer content, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_METHOD_ZENENGINE_EVALUATE
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_METHOD_ZENENGINE_EVALUATE
uint64_t uniffi_zen_uniffi_fn_method_zenengine_evaluate(void*_Nonnull ptr, RustBuffer key, RustBuffer context, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_METHOD_ZENENGINE_GET_DECISION
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_METHOD_ZENENGINE_GET_DECISION
uint64_t uniffi_zen_uniffi_fn_method_zenengine_get_decision(void*_Nonnull ptr, RustBuffer key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_CLONE_ZENEXPRESSION
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_CLONE_ZENEXPRESSION
void*_Nonnull uniffi_zen_uniffi_fn_clone_zenexpression(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_FREE_ZENEXPRESSION
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_FREE_ZENEXPRESSION
void uniffi_zen_uniffi_fn_free_zenexpression(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_CONSTRUCTOR_ZENEXPRESSION_COMPILE
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_CONSTRUCTOR_ZENEXPRESSION_COMPILE
void*_Nonnull uniffi_zen_uniffi_fn_constructor_zenexpression_compile(RustBuffer expression, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_METHOD_ZENEXPRESSION_EVALUATE
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_METHOD_ZENEXPRESSION_EVALUATE
RustBuffer uniffi_zen_uniffi_fn_method_zenexpression_evaluate(void*_Nonnull ptr, RustBuffer context, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_CLONE_ZENEXPRESSIONUNARY
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_CLONE_ZENEXPRESSIONUNARY
void*_Nonnull uniffi_zen_uniffi_fn_clone_zenexpressionunary(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_FREE_ZENEXPRESSIONUNARY
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_FREE_ZENEXPRESSIONUNARY
void uniffi_zen_uniffi_fn_free_zenexpressionunary(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_CONSTRUCTOR_ZENEXPRESSIONUNARY_COMPILE
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_CONSTRUCTOR_ZENEXPRESSIONUNARY_COMPILE
void*_Nonnull uniffi_zen_uniffi_fn_constructor_zenexpressionunary_compile(RustBuffer expression, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_METHOD_ZENEXPRESSIONUNARY_EVALUATE
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_METHOD_ZENEXPRESSIONUNARY_EVALUATE
int8_t uniffi_zen_uniffi_fn_method_zenexpressionunary_evaluate(void*_Nonnull ptr, RustBuffer context, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_INIT_CALLBACK_VTABLE_ZENCUSTOMNODECALLBACK
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_INIT_CALLBACK_VTABLE_ZENCUSTOMNODECALLBACK
void uniffi_zen_uniffi_fn_init_callback_vtable_zencustomnodecallback(const UniffiVTableCallbackInterfaceZenCustomNodeCallback* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_INIT_CALLBACK_VTABLE_ZENDECISIONLOADERCALLBACK
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_INIT_CALLBACK_VTABLE_ZENDECISIONLOADERCALLBACK
void uniffi_zen_uniffi_fn_init_callback_vtable_zendecisionloadercallback(const UniffiVTableCallbackInterfaceZenDecisionLoaderCallback* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_FUNC_EVALUATE_EXPRESSION
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_FUNC_EVALUATE_EXPRESSION
RustBuffer uniffi_zen_uniffi_fn_func_evaluate_expression(RustBuffer expression, RustBuffer context, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_FUNC_EVALUATE_UNARY_EXPRESSION
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_FUNC_EVALUATE_UNARY_EXPRESSION
int8_t uniffi_zen_uniffi_fn_func_evaluate_unary_expression(RustBuffer expression, RustBuffer context, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_FUNC_OVERRIDE_CONFIG
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_FN_FUNC_OVERRIDE_CONFIG
void uniffi_zen_uniffi_fn_func_override_config(RustBuffer config, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUSTBUFFER_ALLOC
RustBuffer ffi_zen_uniffi_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_zen_uniffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUSTBUFFER_FREE
void ffi_zen_uniffi_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUSTBUFFER_RESERVE
RustBuffer ffi_zen_uniffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_U8
void ffi_zen_uniffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_U8
void ffi_zen_uniffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_U8
void ffi_zen_uniffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_zen_uniffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_I8
void ffi_zen_uniffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_I8
void ffi_zen_uniffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_I8
void ffi_zen_uniffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_zen_uniffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_U16
void ffi_zen_uniffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_U16
void ffi_zen_uniffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_U16
void ffi_zen_uniffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_zen_uniffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_I16
void ffi_zen_uniffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_I16
void ffi_zen_uniffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_I16
void ffi_zen_uniffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_zen_uniffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_U32
void ffi_zen_uniffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_U32
void ffi_zen_uniffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_U32
void ffi_zen_uniffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_zen_uniffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_I32
void ffi_zen_uniffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_I32
void ffi_zen_uniffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_I32
void ffi_zen_uniffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_zen_uniffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_U64
void ffi_zen_uniffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_U64
void ffi_zen_uniffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_U64
void ffi_zen_uniffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_zen_uniffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_I64
void ffi_zen_uniffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_I64
void ffi_zen_uniffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_I64
void ffi_zen_uniffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_zen_uniffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_F32
void ffi_zen_uniffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_F32
void ffi_zen_uniffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_F32
void ffi_zen_uniffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_F32
float ffi_zen_uniffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_F64
void ffi_zen_uniffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_F64
void ffi_zen_uniffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_F64
void ffi_zen_uniffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_F64
double ffi_zen_uniffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_POINTER
void ffi_zen_uniffi_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_POINTER
void ffi_zen_uniffi_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_POINTER
void ffi_zen_uniffi_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_zen_uniffi_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_zen_uniffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_zen_uniffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_zen_uniffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_zen_uniffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_POLL_VOID
void ffi_zen_uniffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_CANCEL_VOID
void ffi_zen_uniffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_FREE_VOID
void ffi_zen_uniffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_RUST_FUTURE_COMPLETE_VOID
void ffi_zen_uniffi_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_FUNC_EVALUATE_EXPRESSION
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_FUNC_EVALUATE_EXPRESSION
uint16_t uniffi_zen_uniffi_checksum_func_evaluate_expression(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_FUNC_EVALUATE_UNARY_EXPRESSION
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_FUNC_EVALUATE_UNARY_EXPRESSION
uint16_t uniffi_zen_uniffi_checksum_func_evaluate_unary_expression(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_FUNC_OVERRIDE_CONFIG
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_FUNC_OVERRIDE_CONFIG
uint16_t uniffi_zen_uniffi_checksum_func_override_config(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_METHOD_ZENDECISION_EVALUATE
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_METHOD_ZENDECISION_EVALUATE
uint16_t uniffi_zen_uniffi_checksum_method_zendecision_evaluate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_METHOD_ZENDECISION_VALIDATE
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_METHOD_ZENDECISION_VALIDATE
uint16_t uniffi_zen_uniffi_checksum_method_zendecision_validate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_METHOD_ZENENGINE_CREATE_DECISION
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_METHOD_ZENENGINE_CREATE_DECISION
uint16_t uniffi_zen_uniffi_checksum_method_zenengine_create_decision(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_METHOD_ZENENGINE_EVALUATE
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_METHOD_ZENENGINE_EVALUATE
uint16_t uniffi_zen_uniffi_checksum_method_zenengine_evaluate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_METHOD_ZENENGINE_GET_DECISION
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_METHOD_ZENENGINE_GET_DECISION
uint16_t uniffi_zen_uniffi_checksum_method_zenengine_get_decision(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_METHOD_ZENEXPRESSION_EVALUATE
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_METHOD_ZENEXPRESSION_EVALUATE
uint16_t uniffi_zen_uniffi_checksum_method_zenexpression_evaluate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_METHOD_ZENEXPRESSIONUNARY_EVALUATE
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_METHOD_ZENEXPRESSIONUNARY_EVALUATE
uint16_t uniffi_zen_uniffi_checksum_method_zenexpressionunary_evaluate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_CONSTRUCTOR_ZENENGINE_NEW
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_CONSTRUCTOR_ZENENGINE_NEW
uint16_t uniffi_zen_uniffi_checksum_constructor_zenengine_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_CONSTRUCTOR_ZENEXPRESSION_COMPILE
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_CONSTRUCTOR_ZENEXPRESSION_COMPILE
uint16_t uniffi_zen_uniffi_checksum_constructor_zenexpression_compile(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_CONSTRUCTOR_ZENEXPRESSIONUNARY_COMPILE
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_CONSTRUCTOR_ZENEXPRESSIONUNARY_COMPILE
uint16_t uniffi_zen_uniffi_checksum_constructor_zenexpressionunary_compile(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_METHOD_ZENCUSTOMNODECALLBACK_HANDLE
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_METHOD_ZENCUSTOMNODECALLBACK_HANDLE
uint16_t uniffi_zen_uniffi_checksum_method_zencustomnodecallback_handle(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_METHOD_ZENDECISIONLOADERCALLBACK_LOAD
#define UNIFFI_FFIDEF_UNIFFI_ZEN_UNIFFI_CHECKSUM_METHOD_ZENDECISIONLOADERCALLBACK_LOAD
uint16_t uniffi_zen_uniffi_checksum_method_zendecisionloadercallback_load(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_ZEN_UNIFFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_zen_uniffi_uniffi_contract_version(void
    
);
#endif

